services:
  taloflash:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 capstone.wsgi:application
    volumes:
      - static_volume:/app/staticfiles
      - ./db_data:/app/db_data
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - taloflash

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run taloflash
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - nginx
    network_mode: "host"

volumes:
  static_volume: