# Generated by Django 4.2.19 on 2025-06-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloflash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='flashSetDisplayOrder',
            field=models.CharField(choices=[('likes', 'Most liked'), ('name', 'Name'), ('newest', 'Newest'), ('creator', "Creator's name")], default='newest', max_length=63),
        ),
    ]
