# Generated by Django 4.2.19 on 2025-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloflash', '0002_alter_settings_flashsetdisplayorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='flashcardDisplayOrder',
            field=models.CharField(choices=[('random', 'Random'), ('newest', 'Newest'), ('alphabeticalFront', 'Alphabetical - front side)'), ('alphabeticalBack', 'Alphabetical - back side')], default='random', max_length=63),
        ),
    ]
