# Generated by Django 4.2.19 on 2025-08-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloflash', '0003_alter_settings_flashcarddisplayorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='flashSetDisplayOrder',
            field=models.CharField(choices=[('likes', 'Most liked'), ('name', 'Name'), ('newest', 'Newest'), ('creator', "Creator's name")], default='likes', max_length=63),
        ),
    ]
