# Generated by Django 4.2.19 on 2025-08-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloflash', '0005_alter_settings_flashcarddisplayorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='hardcoreMode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='timeLimitBehavior',
            field=models.CharField(choices=[('nothing', 'Nothing'), ('show', 'Show'), ('kick', 'Kick'), ('restart', 'Restart')], default='nothing', max_length=63),
        ),
        migrations.AddField(
            model_name='settings',
            name='timerBehavior',
            field=models.CharField(choices=[('countDown', 'Count down'), ('countUp', 'Count up')], default='countDown', max_length=63),
        ),
    ]
