# Generated by Django 4.2.19 on 2025-08-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloflash', '0006_settings_hardcoremode_settings_timelimitbehavior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='flashcardFontSize',
            field=models.IntegerField(default=64),
        ),
    ]
