# Generated by Django 4.2.19 on 2025-08-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloflash', '0007_alter_settings_flashcardfontsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='flashcardDisplayOrder',
            field=models.CharField(choices=[('random', 'Random'), ('oldest', 'Oldest'), ('alphabeticalFront', 'Alphabetical - front side)'), ('alphabeticalBack', 'Alphabetical - back side')], default='oldest', max_length=63),
        ),
        migrations.AlterField(
            model_name='settings',
            name='flashcardFontSize',
            field=models.IntegerField(default=40),
        ),
    ]
