# Generated by Django 4.2.19 on 2025-08-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taloflash', '0008_alter_settings_flashcarddisplayorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='timerBehavior',
        ),
    ]
