# Generated by Django 4.2.19 on 2025-08-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloflash', '0009_remove_settings_timerbehavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='timeLimitBehavior',
            field=models.CharField(choices=[('nothing', 'Nothing'), ('kick', 'Kick'), ('restart', 'Restart')], default='nothing', max_length=63),
        ),
    ]
