# Generated by Django 4.2.19 on 2025-08-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taloflash', '0010_alter_settings_timelimitbehavior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='learners',
        ),
    ]
